services:

  db:
    image: postgres
    restart: always
    
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db

      
    ports:
      - 5432:5432
